spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:project101;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: vagrant
    password: vagrant
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: create

  flyway:
    baseline-on-migrate: true

  h2:
    console:
      enabled: true
